apps/ventas/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('apps.ventas.views',
    # URLs Ventas
    url(r'list/', 'ventas'),
    url(r'del/(?P<id>\d+)', 'del_ventas'),
    url(r'edit/(?P<id>\d+)', 'edit_ventas'),
    url(r'add/', 'add_ventas'),
    url(r'detail/(?P<id>\d+)', 'detail_ventas'),
    url(r'entregas/$', 'lista_entregas'), # ACTIVOS
    url(r'devolver/(?P<id>\d+)/$', 'entregar'),
    url(r'checkout/(?P<id>\d+)/$', 'checkout'),
    url(r'finished/$', 'terminadas'), # TERMINADAS
    url(r'reportes/$', 'reportes'),
    url(r'pendientes/$', 'pendientes'), # CREDITO
    # URL Reservaciones
    url(r'reservaciones', 'reservaciones'),
    url(r'reservacion/borrar/(?P<id>\d+)', 'del_reservaciones'),
    url(r'reservacion/editar/(?P<id>\d+)', 'edit_reservaciones'),
    url(r'reservacion/agregar/', 'add_reservaciones'),
    url(r'reservacion/vender/(?P<id>\d+)/$', 'vender_reservaciones'),
)

urlpatterns += patterns('apps.ventas.reports.pdf',
    url(r'reservacion/print/(?P<id>\d+)/$', 'print_reserva', name='print-reserva'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView


admin.autodiscover()


urlpatterns = patterns('',
    url(r'^autos/', include('apps.autos.urls')),
    url(r'^clientes/', include('apps.clientes.urls')),
    url(r'^ventas/', include('apps.ventas.urls')),
    url(r'^panel/', include('apps.admin.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^panel/$', TemplateView.as_view(template_name="index.html")),
)


urlpatterns += patterns('',
    url(r'^panel/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^panel/logout/$', 'django.contrib.auth.views.logout_then_login'),
)

apps/ventas/models.py
from django.db import models
from apps.autos.models import Autos
from apps.clientes.models import Clientes
from django.contrib.auth.models import User
from datetime import datetime


class Ventas(models.Model): 
    """ 
    Modelo de Rentas de los autos
    Require modelos:
        Autos
        Clientes"""
    TIPOS_PAGO = (
        ('EFECTIVO','EFECTIVO'),
        ('TARJETA', 'TARJETA'),
        ('PENDIENTE', 'PENDIENTE'),
    )
    TIPOS_TARJETA = (
        ('VISA', 'VISA'),
        ('AMERICAN', 'AMERICAN EXPRESS'),
        ('MASTERCARD', 'MASTERCARD'),
    )
    SERIE = (
        ('C','C'), # Fiscal
        ('D', 'D'), # No fiscal
    )
    auto = models.ForeignKey(Autos)
    cliente = models.ForeignKey(Clientes)
    vendedor = models.ForeignKey(User)
    km_entrada = models.PositiveIntegerField(default=0)
    km_salida = models.PositiveIntegerField(default=0)
    km_recorridos = models.PositiveIntegerField(default=0)
    finalizada = models.BooleanField(default=False)
    fecha_salida = models.DateTimeField()
    created_at = models.DateTimeField(default=datetime.now())
    hora_extra = models.IntegerField(default = 0)
    fecha_entrada = models.DateTimeField(null=True)
    preciodia = models.FloatField(null=True, verbose_name="Precio Por Dia")
    seguro_accidentes = models.BooleanField(default=False)
    seguro_colision = models.BooleanField(default=False)
    tiene_conductor = models.BooleanField(default=False)
    nombre_conductor = models.CharField(max_length=500, blank=True, null=True)
    licencia_conductor = models.CharField(blank=True, null=True, max_length=100)
    lic_vencimiento_conductor = models.DateField(blank=True, null=True)
    lic_expedicion_conductor = models.DateField(blank=True, null=True)
    deposito = models.FloatField(default=0)
    adelanto = models.FloatField(default=0)
    iva = models.BooleanField(verbose_name="Con/Sin IVA")
    gas_octavos_entrada = models.IntegerField(null=True, 
                            verbose_name="Octavos de Gas")
    gas_octavos_salida = models.IntegerField(verbose_name="Octavos de Gas")
    reembolso = models.FloatField(default=0)
    total_iva = models.FloatField(default=0)
    total_horaextra = models.FloatField(default=0)
    total_dias = models.FloatField(default=0) # Dinero de renta
    total_gas = models.FloatField(default=0)
    total_seguros = models.FloatField(default=0)
    total_conductor = models.FloatField(default=0)
    total = models.FloatField(null=True)
    danios = models.FloatField(default=0)
    dias = models.PositiveIntegerField() # Numero dias que se rento
    tipo_pago = models.CharField(max_length=30, choices=TIPOS_PAGO)
    tarjeta = models.CharField(max_length=50, choices=TIPOS_TARJETA,
        verbose_name="Tipo de Tarjeta", null=True, blank=True)
    tar_vencimiento = models.DateField(verbose_name="Fecha Vencimiento", 
                                        null=True, blank=True)
    tar_numero = models.IntegerField(verbose_name="Numero Tarjeta", 
                                     blank=True ,null=True)
    num_contrato = models.PositiveIntegerField()
    serie = models.CharField(max_length=1, choices=SERIE)
    comentarios = models.TextField(max_length=255, blank=True)


class Reservaciones(models.Model):
    """
    Modelo de reservaciones
     Require modelos:
        Autos
        Clientes"""
    auto = models.ForeignKey(Autos)
    cliente = models.CharField(max_length=500, blank=True)
    fecha = models.DateTimeField()
    hotel = models.CharField(max_length=500, blank=True, 
            verbose_name="Hotel")
    num_cuarto = models.CharField(max_length=500, blank=True, 
            verbose_name="Num. Cuarto")
    anticipo = models.CharField(max_length=500, blank=True)
    comentarios = models.TextField(max_length=255, blank=True)
    created_at = models.DateTimeField(default=datetime.now())

apps/ventas/views.py
# encoding: latin-1
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.contrib.auth.decorators import permission_required, login_required
from django.template import RequestContext
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from apps.ventas.models import Ventas, Reservaciones
from apps.ventas.forms import ReservacionesForm, VentasCompleteForm, \
     VentasForm, VentasReturnForm, ReporteVentasForm
from django.contrib import messages
from apps.admin.models import Precios
from apps.eonutils.forms import DivErrorList
from datetime import datetime, time
from django.db.models import Sum, Q


@login_required
def reservaciones(request):
    reservacion = Reservaciones.objects.all().order_by('fecha')
    paginator = Paginator(reservacion, 30) 
    
     # Make sure page request is an int. If not, deliver first page.
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    # If page request (9999) is out of range, deliver last page of results.
    try:
        reservacion_pagina = paginator.page(page)
    except (EmptyPage, InvalidPage):
        reservacion_pagina = paginator.page(paginator.num_pages)
    
    vars = { 'reservaciones' : reservacion_pagina }
    
    return render_to_response('ventas/reservaciones.html', vars,
                                 RequestContext(request))


@permission_required('ventas.delete_reservaciones')
def del_reservaciones(request, id):
    reservacion = get_object_or_404(Reservaciones, pk = id)
    reservacion.delete()
    return redirect('/ventas/reservaciones/?s=1')


@permission_required('ventas.add_reservaciones')
def add_reservaciones(request):
    if request.method == 'POST':
        form = ReservacionesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/ventas/reservaciones/', 
                            context_instance = RequestContext(request))
    else:
        form = ReservacionesForm()
    vars = {'form' : form}
    return render_to_response('ventas/add_reservaciones.html', vars,
                                    context_instance = RequestContext(request))


@permission_required('ventas.change_reservaciones')
def edit_reservaciones(request, id):
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    
    if request.method == 'POST':
        reservacion = get_object_or_404(Reservaciones, pk = id)
        form = ReservacionesForm(request.POST, instance=reservacion)
        if form.is_valid():
            form.save()
        return redirect('/ventas/reservaciones/?page=' + str(page), 
                            context_instance = RequestContext(request))
    else:
        reservacion = get_object_or_404(Reservaciones, pk = id)
        form = ReservacionesForm(instance = reservacion)
    vars = { 'form' : form, 'reservacion' : reservacion, 'page' : page }
    return render_to_response('ventas/change_reservaciones.html', vars,
                                context_instance = RequestContext(request))


@permission_required('ventas.add_ventas')
def vender_reservaciones(request, id):
    reserva = get_object_or_404(Reservaciones, pk=id)
    form = VentasForm(
                        {'fecha_salida': reserva.fecha,
                         'auto': reserva.auto,
                         'comentarios': reserva.comentarios,
                         'adelanto': reserva.anticipo,
                        }
                    )
    reserva.delete()
    messages.success(request, 'Se ha eliminado de la lista de reservaciones.')
    vars = {'form': form}
    return render_to_response('ventas/add_ventas.html', vars,
                                    context_instance = RequestContext(request))


# Ventas
@login_required
def ventas(request):
    ventas = Ventas.objects.all().order_by('serie').order_by('-num_contrato')
    paginator = Paginator(ventas, 20) 
    
     # Make sure page request is an int. If not, deliver first page.
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    # If page request (9999) is out of range, deliver last page of results.
    try:
        venta_pagina = paginator.page(page)
    except (EmptyPage, InvalidPage):
        venta_pagina = paginator.page(paginator.num_pages)
    
    vars = { 'ventas' : venta_pagina }
    
    return render_to_response('ventas/ventas.html', vars,
                                 RequestContext(request))


@permission_required('ventas.delete_ventas')
def del_ventas(request, id):
    venta = get_object_or_404(Ventas, pk = id)
    venta.delete()
    messages.error(request, 'La venta ha sido eliminada.')
    return redirect('/ventas/list/')


@permission_required('ventas.add_ventas')
def add_ventas(request):
    if request.method == 'POST':
        form = VentasForm(request.POST, error_class=DivErrorList)
        if form.is_valid():
            venta = form.save(commit=False)
            venta.vendedor = request.user
            if venta.tipo_pago == "PENDIENTE":
                venta.reembolso = 1
            venta.save()
            messages.success(request, 'Venta agregada correctamente.')
            return redirect('/ventas/entregas/', 
                            context_instance = RequestContext(request))
    else:
        form = VentasForm()
    vars = {'form' : form}
    return render_to_response('ventas/add_ventas.html', vars,
                                    context_instance = RequestContext(request))


@permission_required('ventas.change_ventas')
def edit_ventas(request, id):
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    
    if request.method == 'POST':
        venta = get_object_or_404(Ventas, pk=id)
        form = VentasForm(request.POST, instance=venta, 
                error_class=DivErrorList)
        if form.is_valid():
            venta = form.save(commit=False)
            venta.vendedor = request.user
            venta.save()
            messages.success(request, 'Venta Actualizada.')
            return redirect('/ventas/list/?page=' + str(page), 
                            context_instance=RequestContext(request))
    else:
        venta = get_object_or_404(Ventas, pk=id)
        form = VentasForm(instance=venta)
    vars = {'form': form, 'venta': venta, 'page': page}
    return render_to_response('ventas/change_ventas.html', vars,
                                context_instance=RequestContext(request))


@login_required
def detail_ventas(request, id):
    venta = get_object_or_404(Ventas, pk=id)
    vars = {'venta': venta}
    return render_to_response('ventas/checkout.html', vars,
                                context_instance=RequestContext(request))


@login_required
def lista_entregas(request):
    entregas = Ventas.objects.filter(finalizada = False)
    entregas = entregas.order_by('-num_contrato')
    
    vars = {'ventas': entregas}
    return render_to_response('ventas/lista_entregas.html', vars,
                                context_instance=RequestContext(request))


@login_required
def entregar(request, id):
    if request.method == 'POST':
        venta = get_object_or_404(Ventas, pk=id)
        form = VentasReturnForm(request.POST, instance=venta)
        if form.is_valid():
            precios = Precios.objects.latest('hora_extra')
            f = form.save(commit=False)
            f.finalizada = True
            days = abs((f.fecha_salida.date() - f.fecha_entrada.date()).days)
            f.total_dias = f.preciodia * days
            f.total_horaextra = f.hora_extra * precios.hora_extra
            f.total_gas = (f.gas_octavos_salida - f.gas_octavos_entrada) * precios.octavo_gas 
            f.total = f.total_gas + f.total_dias + f.total_horaextra
            f.km_recorridos = f.km_entrada - f.km_salida
            if f.seguro_accidentes:
                f.total += precios.seguro_accidentes
                f.total_seguros = precios.seguro_accidentes 
            if f.seguro_colision:
                f.total += precios.seguro_colision * days
                f.total_seguros += precios.seguro_colision * days
            if f.iva:
                f.total_iva = f.total * 0.11
                f.total += f.total * 0.11
            if f.tiene_conductor:
                f.total_conductor = precios.conductor
                f.total += precios.conductor
            f.save()
            messages.success(request, 'Entrega Registrada.')
            return redirect('/ventas/checkout/%s' % venta.id, 
                            context_instance=RequestContext(request))
    else:
        venta = get_object_or_404(Ventas, pk=id)
        form = VentasReturnForm(instance=venta)
    vars = {'form': form, 'venta': venta}
    return render_to_response('ventas/devolver.html', vars,
                                context_instance=RequestContext(request))


@login_required
def checkout(request, id):
    venta = get_object_or_404(Ventas, pk=id)
    if venta.finalizada:
        vars = {'venta' : venta}
        return render_to_response('ventas/checkout.html', vars,
                                context_instance=RequestContext(request))
    else:
        return redirect('/ventas/devolver/%s' % venta.id)


def terminadas(request):
    if request.method == 'POST':
        q = request.POST["q"]
        finalizadas = Ventas.objects.filter(
                Q(num_contrato__icontains=q)
        )
    else:
        finalizadas = Ventas.objects.filter(finalizada = True)
    finalizadas = finalizadas.order_by('serie')
    finalizadas = finalizadas.order_by('-num_contrato')
    
    paginator = Paginator(finalizadas, 20) 
    
     # Make sure page request is an int. If not, deliver first page.
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    # If page request (9999) is out of range, deliver last page of results.
    try:
        ventas = paginator.page(page)

templates/ventas/add_reservaciones.html
{% extends 'default.html' %}

{%  block content%}
<h3>Agregar reservacion</h3>

    <form action="." class="well" method="POST"> {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Guardar" />
    </form>
{% endblock content %}

templates/ventas/add_ventas.html
{% extends 'default.html' %}

{% block head %}
    <script src="/static/assets/js/sales.js" type="text/javascript"></script>
{% endblock %}

{%  block content%}
<h3>Agregar Venta</h3>

    <form action="{% url apps.ventas.views.add_ventas %}" class="form-vertical well" method="POST"> {% csrf_token %}
        {{ form.non_field_errors|safe }}
         <div class="">
            {{ form.num_contrato.errors|safe }}
            {{ form.seria.errors|safe }}
            <label for="id_num_contrato">Numero de Contrato:</label>
            {{ form.num_contrato }} {{ form.serie }}
        </div>
         <div class="">
            {{ form.auto.errors|safe }}
            <label for="id_auto">Auto:</label>
            {{ form.auto }}
        </div>
        <div class="">
            {{ form.cliente.errors|safe }}
            <label for="id_cliente">Cliente:</label>
            {{ form.cliente }}
            <div id="clienteinfo">
                
            </div>
        </div>
        <div class="">
            {{ form.tiene_conductor.errors|safe }}
            <label for="id_tiene_conductor">Conductor:</label>
            {{ form.tiene_conductor }}
        </div>
            <div id="conductor">
                <div class="">
                    {{ form.nombre_conductor.errors|safe }}
                    <label for="id_nombre_conductor">Nombre:</label>
                    {{ form.nombre_conductor }}
                </div>
                <div class="">
                    {{ form.licencia_conductor.errors|safe }}
                    <label for="id_lic_conductor"># Licencia:</label>
                    {{ form.licencia_conductor }}
                </div>
                <div class="">
                    {{ form.lic_vencimiento_conductor.errors|safe }}
                    <label for="id_lic_vencimiento_conductor">Fecha Vencimiento:</label>
                    {{ form.lic_vencimiento_conductor }}
                </div>
                <div class="">
                    {{ form.lic_expedicion_conductor.errors|safe }}
                    <label for="id_lic_expedicion_conductor">Fecha Expedicion:</label>
                    {{ form.lic_expedicion_conductor }}
                </div>
            </div>
        <div class="">
            {{ form.fecha_salida.errors|safe }}
            <label for="id_fecha_salida">Fecha Salida:</label>
            {{ form.fecha_salida }}
        </div>
        <div class="">
            {{ form.fecha_entrada.errors|safe }}
            <label for="id_fecha_entrada">Fecha Entrada:</label>
            {{ form.fecha_entrada }}
        </div>
        <div class="">
            {{ form.dias.errors|safe }}
            <label for="id_dias">Días:</label>
            <h1 id="dias"></h1>
            {{ form.dias }}
        </div>
        <div class="">
            {{ form.seguro_accidentes.errors|safe }}
            {{ form.seguro_colision.errors|safe }}
            <label for="id_seguro_accidentes">Seguros:</label>
            Accidentes: {{ form.seguro_accidentes }} Colision: {{ form.seguro_colision }}
        </div>
        <div class="input-prepend">
            {{ form.deposito.errors|safe }}
            <label for="id_deposito">Deposito en Garantia:</label>
            <span class="add-on">$</span>
            {{ form.deposito }}
        </div>
        <div class="input-prepend">
            {{ form.adelanto.errors|safe }}
            <label for="id_adelanto">Adelanto:</label>
            <span class="add-on">$</span>
            {{ form.adelanto }}
        </div>
        <div class="">
            {{ form.iva.errors|safe }}
            <label for="id_iva">Agregar IVA:</label>
            {{ form.iva }}
        </div>
        <div class="input-prepend">
            {{ form.preciodia.errors|safe }}
            <label for="id_preciodia">Precio Por Día:</label>
            <span class="add-on">$</span>
            {{ form.preciodia }}
        </div>

        <div class="gas">
            {{ form.octavo_gas_salida.errors|safe }}
            <label for="id_gas_octavos_salida_0">Gasolina:</label>
            <ul>
                <li ><label for="id_gas_octavos_salida_0"><input type="radio" id="id_gas_octavos_salida_0" value="1" name="gas_octavos_salida"> 1/8</label></li>
                <li><label for="id_gas_octavos_salida_1"><input type="radio" id="id_gas_octavos_salida_1" value="2" name="gas_octavos_salida"> 2/8</label></li>
                <li><label for="id_gas_octavos_salida_2"><input type="radio" id="id_gas_octavos_salida_2" value="3" name="gas_octavos_salida"> 3/8</label></li>
                <li><label for="id_gas_octavos_salida_3"><input type="radio" id="id_gas_octavos_salida_3" value="4" name="gas_octavos_salida"> 4/8</label></li>
                <li><label for="id_gas_octavos_salida_4"><input type="radio" id="id_gas_octavos_salida_4" value="5" name="gas_octavos_salida"> 5/8</label></li>
                <li><label for="id_gas_octavos_salida_5"><input type="radio" id="id_gas_octavos_salida_5" value="6" name="gas_octavos_salida"> 6/8</label></li>
                <li><label for="id_gas_octavos_salida_6"><input type="radio" id="id_gas_octavos_salida_6" value="7" name="gas_octavos_salida"> 7/8</label></li>
                <li><label for="id_gas_octavos_salida_7"><input type="radio" id="id_gas_octavos_salida_7" value="8" name="gas_octavos_salida"> 8/8</label></li>
            </ul>
        </div>
        <div class="clearfix"></div>
        <div class="">
            {{ form.comentarios.errors|safe }}
            <label for="id_comentarios">Comentarios:</label>
            {{ form.comentarios }}
        </div>
       <div class="">
            {{ form.tipo_pago.errors|safe }}
            <label for="id_tipo_pago">Tipo de Pago:</label>
            {{ form.tipo_pago }}
        </div>
        <div class="">
            {{ form.km_salida.errors|safe }}
            <label for="id_km_salida">Kilometraje:</label>
            {{ form.km_salida }}
        </div>
        <div id="tarjeta">
            <div class="">
                {{ form.tarjeta.errors|safe }}
                <label for="id_tarjeta">Tipo de Tarjeta:</label>
                {{ form.tarjeta }}
            </div>
            <div class="">
                {{ form.tar_numero.errors|safe }}
                <label for="id_tar_numero"># Tarjeta:</label>
                {{ form.tar_numero }}
            </div>
            <div class="">
                {{ form.tar_vencimiento.errors|safe }}
                <label for="id_tar_vencimiento">Fecha Vencimiento:</label>
                {{ form.tar_vencimiento }}
            </div>
            {{ form.total }}
        </div>
        <div class="page-header">
          <h1 >Total: <span id="total"></span></h1>
        </div>
        
        <input type="submit" class="btn btn-success" value="Guardar" />
    </form>
{% endblock content %}

templates/ventas/change_reservaciones.html
{% extends 'default.html' %}

{%  block content%}
<h3>Editar reservación</h3>
	
	<form action="{% url apps.ventas.views.edit_reservaciones reservacion.id %}" class="well" method="POST"> {% csrf_token %}
		{{ form.as_p }}
		<input type="submit" class="btn btn-success" value="Guardar" />
	</form>
{% endblock content %}

templates/ventas/change_ventas.html
{% extends 'default.html' %}

{% block head %}
    <script src="/static/assets/js/sales.js" type="text/javascript"></script>
{% endblock %}

{%  block content%}
<h3>Editar Venta: {{ venta.num_contrato }}</h3>

    <form action="{% url apps.ventas.views.edit_ventas venta.id %}" class="form-vertical well" method="POST"> {% csrf_token %}
        {{ form.non_field_errors|safe }}
         <div class="">
            {{ form.num_contrato.errors|safe }}
            {{ form.seria.errors|safe }}
            <label for="id_num_contrato">Numero de Contrato:</label>
            {{ form.num_contrato }} {{ form.serie }}
        </div>
         <div class="">
            {{ form.auto.errors|safe }}
            <label for="id_auto">Auto:</label>
            {{ form.auto }}
        </div>
        <div class="">
            {{ form.cliente.errors|safe }}
            <label for="id_cliente">Cliente:</label>
            {{ form.cliente }}
            <div id="clienteinfo">
                
            </div>
        </div>
        <div class="">
            {{ form.tiene_conductor.errors|safe }}
            <label for="id_tiene_conductor">Conductor:</label>
            {{ form.tiene_conductor }}
        </div>
            <div id="conductor">
                <div class="">
                    {{ form.nombre_conductor.errors|safe }}
                    <label for="id_nombre_conductor">Nombre:</label>
                    {{ form.nombre_conductor }}
                </div>
                <div class="">
                    {{ form.licencia_conductor.errors|safe }}
                    <label for="id_lic_conductor"># Licencia:</label>
                    {{ form.licencia_conductor }}
                </div>
                <div class="">
                    {{ form.lic_vencimiento_conductor.errors|safe }}
                    <label for="id_lic_vencimiento_conductor">Fecha Vencimiento:</label>
                    {{ form.lic_vencimiento_conductor }}
                </div>
                <div class="">
                    {{ form.lic_expedicion_conductor.errors|safe }}
                    <label for="id_lic_expedicion_conductor">Fecha Expedicion:</label>
                    {{ form.lic_expedicion_conductor }}
                </div>
            </div>
        <div class="">
            {{ form.fecha_salida.errors|safe }}
            <label for="id_fecha_salida">Fecha Salida:</label>
            {{ form.fecha_salida }}
        </div>
        <div class="">
            {{ form.fecha_entrada.errors|safe }}
            <label for="id_fecha_entrada">Fecha Entrada:</label>
            {{ form.fecha_entrada }}
        </div>
        <div class="">
            {{ form.dias.errors|safe }}
            <label for="id_dias">Días:</label>
            <h1 id="dias"></h1>
            {{ form.dias }}
        </div>
        <div class="">
            {{ form.seguro_accidentes.errors|safe }}
            {{ form.seguro_colision.errors|safe }}
            <label for="id_seguro_accidentes">Seguros:</label>
            Accidentes: {{ form.seguro_accidentes }} Colision: {{ form.seguro_colision }}
        </div>
        <div class="input-prepend">
            {{ form.deposito.errors|safe }}
            <label for="id_deposito">Deposito en Garantia:</label>
            <span class="add-on">$</span>
            {{ form.deposito }}
        </div>
        <div class="input-prepend">
            {{ form.adelanto.errors|safe }}
            <label for="id_adelanto">Adelanto:</label>
            <span class="add-on">$</span>
            {{ form.adelanto }}
        </div>
        <div class="">
            {{ form.iva.errors|safe }}
            <label for="id_iva">Agregar IVA:</label>
            {{ form.iva }}
        </div>
        <div class="input-prepend">
            {{ form.preciodia.errors|safe }}
            <label for="id_preciodia">Precio Por Día:</label>
            <span class="add-on">$</span>
            {{ form.preciodia }}
        </div>

        <div class="gas">
            {{ form.octavo_gas_salida.errors|safe }}
            <label for="id_gas_octavos_salida_0">Gasolina:</label>
            <ul>
                <li ><label for="id_gas_octavos_salida_0"><input type="radio" id="id_gas_octavos_salida_0" value="1" name="gas_octavos_salida"> 1/8</label></li>
                <li><label for="id_gas_octavos_salida_1"><input type="radio" id="id_gas_octavos_salida_1" value="2" name="gas_octavos_salida"> 2/8</label></li>
                <li><label for="id_gas_octavos_salida_2"><input type="radio" id="id_gas_octavos_salida_2" value="3" name="gas_octavos_salida"> 3/8</label></li>
                <li><label for="id_gas_octavos_salida_3"><input type="radio" id="id_gas_octavos_salida_3" value="4" name="gas_octavos_salida"> 4/8</label></li>
                <li><label for="id_gas_octavos_salida_4"><input type="radio" id="id_gas_octavos_salida_4" value="5" name="gas_octavos_salida"> 5/8</label></li>
                <li><label for="id_gas_octavos_salida_5"><input type="radio" id="id_gas_octavos_salida_5" value="6" name="gas_octavos_salida"> 6/8</label></li>
                <li><label for="id_gas_octavos_salida_6"><input type="radio" id="id_gas_octavos_salida_6" value="7" name="gas_octavos_salida"> 7/8</label></li>
                <li><label for="id_gas_octavos_salida_7"><input type="radio" id="id_gas_octavos_salida_7" value="8" name="gas_octavos_salida"> 8/8</label></li>
            </ul>
        </div>
        <div class="clearfix"></div>
        <div class="">
            {{ form.comentarios.errors|safe }}
            <label for="id_comentarios">Comentarios:</label>
            {{ form.comentarios }}
        </div>
       <div class="">
            {{ form.tipo_pago.errors|safe }}
            <label for="id_tipo_pago">Tipo de Pago:</label>
            {{ form.tipo_pago }}
        </div>
        <div class="">
            {{ form.km_salida.errors|safe }}
            <label for="id_km_salida">Kilometraje:</label>
            {{ form.km_salida }}
        </div>
        <div id="tarjeta">
            <div class="">
                {{ form.tarjeta.errors|safe }}
                <label for="id_tarjeta">Tipo de Tarjeta:</label>
                {{ form.tarjeta }}
            </div>
            <div class="">
                {{ form.tar_numero.errors|safe }}
                <label for="id_tar_numero"># Tarjeta:</label>
                {{ form.tar_numero }}
            </div>
            <div class="">
                {{ form.tar_vencimiento.errors|safe }}
                <label for="id_tar_vencimiento">Fecha Vencimiento:</label>
                {{ form.tar_vencimiento }}
            </div>
            {{ form.total }}
        </div>
        <div class="page-header">
          <h1 >Total: <span id="total"></span></h1>
        </div>
        
        <input type="submit" class="btn btn-success" value="Guardar" />
    </form>
{% endblock content %}