urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView


admin.autodiscover()


urlpatterns = patterns('',
    url(r'^autos/', include('apps.autos.urls')),
    url(r'^clientes/', include('apps.clientes.urls')),
    url(r'^ventas/', include('apps.ventas.urls')),
    url(r'^panel/', include('apps.admin.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^panel/$', TemplateView.as_view(template_name="index.html")),
)


urlpatterns += patterns('',
    url(r'^panel/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^panel/logout/$', 'django.contrib.auth.views.logout_then_login'),
)

apps/autos/models.py
# encoding: utf-8

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Autos(models.Model):
    Marcas = (
        ('Audi', 'Audi'),
        ('Jeep', 'Jeep'),
        ('Wrangler', 'Wrangler'),
        ('Chevrolet', 'Chevrolet'),
        ('Mercedez', 'Mercedez Benz'),
        ('Ford', 'Ford'),
        ('Nissan', 'Nissan'),
        ('VW', 'VW'),
        ('Fiat', 'Fiat'),
        ('Honda', 'Honda'),
        ('Dodge', 'Dodge'),
        ('Renault', 'Renault'),
        ('Toyota', 'Toyota'),
    )
    codigo = models.CharField(max_length = 55)
    marca = models.CharField(max_length = 255, choices = Marcas)
    modelo = models.CharField(max_length = 255)
    color = models.CharField(max_length = 255)
    anio = models.IntegerField(max_length = 255, verbose_name="Año")
    placas = models.CharField(max_length = 10)
    precio = models.IntegerField(max_length = 255)
    active = models.BooleanField(default = True)

    def __unicode__(self):
        return self.codigo + ' ' + self.placas


class Reparaciones(models.Model):
    auto = models.ForeignKey(Autos)
    descripcion = models.CharField(max_length = 500)
    monto = models.FloatField()
    proveedor = models.CharField(max_length = 255)
    kilometraje = models.IntegerField()
    fecha = models.DateField()

    def __str__(self):
        return self.auto.codigo + ' ' + self.descripcion + ' ' + self.monto

apps/clientes/models.py
# encoding: utf-8
from django.db import models

class Clientes(models.Model):
    nombre = models.CharField(max_length = 255)
    apellidos = models.CharField(max_length = 255)
    edad = models.IntegerField()
    domicilio = models.CharField(max_length = 255)
    telefono = models.CharField(default=0, max_length=15)
    email = models.EmailField(null=True, blank=True)
    licencia = models.CharField(verbose_name="Numero Licencia", max_length=50)
    lic_vencimiento = models.DateField(verbose_name="Vencimiento de Licencia")
    lic_expedicion = models.DateField(verbose_name="Fecha de Expedición")
    tieneFiscal = models.BooleanField(verbose_name="Requiere Factura?")
    fis_nombre = models.CharField(max_length = 255, blank = True,
        verbose_name="Nombre Fiscal")
    fis_domicilio = models.CharField(max_length = 255, blank=True,
        verbose_name="Domicilio Fiscal", null=True)
    fis_rfc = models.CharField(max_length = 255, blank = True,
        verbose_name="RFC")
    fis_telefono = models.CharField(max_length = 255, blank = True,
        verbose_name="Telefono Fiscal")

    def __unicode__(self):
        return self.nombre + ' ' + self.apellidos

apps/ventas/models.py
from django.db import models
from apps.autos.models import Autos
from apps.clientes.models import Clientes
from django.contrib.auth.models import User
from datetime import datetime


class Ventas(models.Model): 
    """ 
    Modelo de Rentas de los autos
    Require modelos:
        Autos
        Clientes"""
    TIPOS_PAGO = (
        ('EFECTIVO','EFECTIVO'),
        ('TARJETA', 'TARJETA'),
        ('PENDIENTE', 'PENDIENTE'),
    )
    TIPOS_TARJETA = (
        ('VISA', 'VISA'),
        ('AMERICAN', 'AMERICAN EXPRESS'),
        ('MASTERCARD', 'MASTERCARD'),
    )
    SERIE = (
        ('C','C'), # Fiscal
        ('D', 'D'), # No fiscal
    )
    auto = models.ForeignKey(Autos)
    cliente = models.ForeignKey(Clientes)
    vendedor = models.ForeignKey(User)
    km_entrada = models.PositiveIntegerField(default=0)
    km_salida = models.PositiveIntegerField(default=0)
    km_recorridos = models.PositiveIntegerField(default=0)
    finalizada = models.BooleanField(default=False)
    fecha_salida = models.DateTimeField()
    created_at = models.DateTimeField(default=datetime.now())
    hora_extra = models.IntegerField(default = 0)
    fecha_entrada = models.DateTimeField(null=True)
    preciodia = models.FloatField(null=True, verbose_name="Precio Por Dia")
    seguro_accidentes = models.BooleanField(default=False)
    seguro_colision = models.BooleanField(default=False)
    tiene_conductor = models.BooleanField(default=False)
    nombre_conductor = models.CharField(max_length=500, blank=True, null=True)
    licencia_conductor = models.CharField(blank=True, null=True, max_length=100)
    lic_vencimiento_conductor = models.DateField(blank=True, null=True)
    lic_expedicion_conductor = models.DateField(blank=True, null=True)
    deposito = models.FloatField(default=0)
    adelanto = models.FloatField(default=0)
    iva = models.BooleanField(verbose_name="Con/Sin IVA")
    gas_octavos_entrada = models.IntegerField(null=True, 
                            verbose_name="Octavos de Gas")
    gas_octavos_salida = models.IntegerField(verbose_name="Octavos de Gas")
    reembolso = models.FloatField(default=0)
    total_iva = models.FloatField(default=0)
    total_horaextra = models.FloatField(default=0)
    total_dias = models.FloatField(default=0) # Dinero de renta
    total_gas = models.FloatField(default=0)
    total_seguros = models.FloatField(default=0)
    total_conductor = models.FloatField(default=0)
    total = models.FloatField(null=True)
    danios = models.FloatField(default=0)
    dias = models.PositiveIntegerField() # Numero dias que se rento
    tipo_pago = models.CharField(max_length=30, choices=TIPOS_PAGO)
    tarjeta = models.CharField(max_length=50, choices=TIPOS_TARJETA,
        verbose_name="Tipo de Tarjeta", null=True, blank=True)
    tar_vencimiento = models.DateField(verbose_name="Fecha Vencimiento", 
                                        null=True, blank=True)
    tar_numero = models.IntegerField(verbose_name="Numero Tarjeta", 
                                     blank=True ,null=True)
    num_contrato = models.PositiveIntegerField()
    serie = models.CharField(max_length=1, choices=SERIE)
    comentarios = models.TextField(max_length=255, blank=True)


class Reservaciones(models.Model):
    """
    Modelo de reservaciones
     Require modelos:
        Autos
        Clientes"""
    auto = models.ForeignKey(Autos)
    cliente = models.CharField(max_length=500, blank=True)
    fecha = models.DateTimeField()
    hotel = models.CharField(max_length=500, blank=True, 
            verbose_name="Hotel")
    num_cuarto = models.CharField(max_length=500, blank=True, 
            verbose_name="Num. Cuarto")
    anticipo = models.CharField(max_length=500, blank=True)
    comentarios = models.TextField(max_length=255, blank=True)
    created_at = models.DateTimeField(default=datetime.now())

templates/default.html
{% load messagestag %}
    
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Pericos - Panel de administración</title>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
        <link rel="author" href="/humans.txt">
        <link rel="shortcut icon" href="/static/assets/images/favicon.png" type="image/png">
        <link rel="apple-touch-icon" href="/static/assets/images/apple-touch-icon.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/static/assets/images/apple-touch-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/static/assets/images/apple-touch-icon-114x114.png">
        <link media="all" rel="stylesheet" href="/static/assets/css/bootstrap.min.css" type="text/css">
        <link media="all" rel="stylesheet" href="/static/assets/css/bootstrap.responsive.min.css" type="text/css">
        <link media="all" rel="stylesheet" href="/static/assets/css/admin.css" type="text/css">
        <link rel="stylesheet" href="/static/assets/css/cupertino/jquery-ui-1.8.20.pycar.css" type="text/css" media="screen" charset="utf-8" />
        <!--Change this for a more properly theme -->
        <script src="/static/assets/js/jquery-1.7.2.min.js" type="text/javascript"></script>
        <script src="/static/assets/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/static/assets/js/sammy.min.js" type="text/javascript"></script>
        <script src="/static/assets/js/admin.js" type="text/javascript"></script>
        <script src="/static/assets/js/sliderAccess.js" type="text/javascript"></script>
        <script src="/static/assets/js/jquery-ui-1.8.16.min.js"></script>
        <script src="/static/assets/js/jquery-ui-timepicker-addon.js"></script>
        <script src="/static/assets/js/jquery.select-to-autocomplete.js"></script>
        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        {% block head %}

        {% endblock %}
    </head>
    <body>

        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="i-bar"></span>
                        <span class="i-bar"></span>
                        <span class="i-bar"></span>
                    </a>
                    <a class="brand" href="/">Pericos</a>
                    <div class="nav-collapse">
                        <ul class="nav pull-left">
                            <li class="active"><a href="#">Dashboard</a></li>
                            <li><a href="#!/apps/list">Aplicaciones</a></li>
                            {% if user.is_staff %}
                                <li><a href="{% url apps.admin.views.config %}">Configuración</a></li>
                            {% endif %}
                            <ul class="nav pull-right">
                            {% if user.is_authenticated %}
                                <li><a href="#"><i class="icon-user icon-white"></i> {{ user.username }}</a></li>
                                <li class="divider-vertical"></li>
                                <li> <a href="{% url django.contrib.auth.views.logout_then_login %}"><i class="icon-exclamation-sign icon-white"></i> Salir</a></li>
                            {% else %}
                                <li><a href="{% url django.contrib.auth.views.login %}">Entrar</a></li>
                            {% endif %}
                            </ul>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row-fluid">
                <div class="span12">
                    <div class="messages">
                        {% render_messages messages %}
                    </div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span2">
                  <div class="well" style="padding: 8px 0;">
                    <ul class="nav nav-list">
                      <li class="active"><a href="#"><i class="icon-home icon-white"></i> Home</a></li>
                      {% if perms.autos.add_autos %}
                      <li class="nav-header"><a href="{% url apps.autos.views.autos %}"><i class="icon-road"></i> Autos</a></li>
                      <ul class="nav nav-list">
                          <li><a href="{% url apps.autos.views.add_autos %}"><i class="icon-plus"></i> Agregar</a></li>
                      </ul>
                      {% endif %}
                      {% if perms.clientes.add_clientes %}
                      <li class="nav-header"><a href="{% url apps.clientes.views.clientes %}"><i class="icon-user"></i> Clientes</a></li>
                      <ul class="nav nav-list">
                          <li><a href="{% url apps.clientes.views.add_clientes %}"><i class="icon-plus"></i> Agregar</a></li>
                          <li></li>
                      </ul>
                      {% endif %}
                      
                      {% if perms.ventas.add_ventas %}
                      <li class="nav-header"><a href="{% url apps.ventas.views.ventas %}"><i class="icon-book"></i> Ventas</a></li>
                      <ul class="nav nav-list">
                          <li><a href="{% url apps.ventas.views.add_ventas %}"><i class="icon-plus"></i> Agregar</a></li>
                          <li><a href="{% url apps.ventas.views.lista_entregas %}"><i class="icon-share"></i> Activos</a></li>
                          <li><a href="{% url apps.ventas.views.terminadas %}"><i class="icon-check"></i> Cerradas</a></li>
                          <li><a href="{% url apps.ventas.views.pendientes %}"><i class="icon-briefcase"></i> Credito</a></li>
                          <li><a href="{% url apps.ventas.views.reportes %}"><i class="icon-list-alt"></i> Reportes</a></li>
                      </ul>
                      {% endif %}
                      {% if perms.ventas.add_reservaciones %}
                      <li class="nav-header"><a href="{% url apps.ventas.views.reservaciones %}"><i class="icon-calendar"></i> Reservas</a></li>
                      <ul class="nav nav-list">
                          <li><a href="{% url apps.ventas.views.add_reservaciones %}"><i class="icon-plus"></i> Agregar</a></li>
                      </ul>
                      {% endif %}
                      {% if perms.autos.add_reparaciones %}
                        <li class="nav-header"><a href="{% url apps.autos.views.lista_autos %}"><i class="icon-wrench"></i> Reparaciones</a></li>
                      {% endif %}
                    </ul>
                  </div> <!-- /well -->
                </div>
                <div class="span10">
                    {% block content %}

                    {% endblock %}
                    <div class="span10">
                        <a class="btn btn-mini btn-primary" href="javascript:history.back()"> <i class="icon-white icon-arrow-left"></i> Regresar</a>
                    </div>
                </div>
            </div>
            <div class="row-fluid">
                <hr>
                <div class="span12">
                    <footer>
                    <p>&copy; <a href="http://eonlabs.net" target="_blank">EonLabs</a> 2012</p>
                    </footer>
                </div>
            </div>
        </div> <!-- /container -->

    </body>
</html>

templates/index.html
{% extends 'default.html' %}

{% block content %}

    <div class="row-fluid">
        <div class="span12">
            <img src="/static/assets/img/header.jpg" alt="Pericos logo" title="Rent a Car" width="" height="" />
        </div>
    </div>
    
{% endblock %}