apps/clientes/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('apps.clientes.views',
    # URLs Clientes
    url(r'list/', 'clientes'),
    url(r'del/(?P<id>\d+)', 'del_clientes'),
    url(r'edit/(?P<id>\d+)/', 'edit_clientes'),
    url(r'add/', 'add_clientes'),
    url(r'detail/(?P<id>\d+)', 'detail_clientes'),
    url(r'api/get/(?P<id>\d+)', 'api_get_client'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView


admin.autodiscover()


urlpatterns = patterns('',
    url(r'^autos/', include('apps.autos.urls')),
    url(r'^clientes/', include('apps.clientes.urls')),
    url(r'^ventas/', include('apps.ventas.urls')),
    url(r'^panel/', include('apps.admin.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^panel/$', TemplateView.as_view(template_name="index.html")),
)


urlpatterns += patterns('',
    url(r'^panel/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^panel/logout/$', 'django.contrib.auth.views.logout_then_login'),
)

apps/clientes/models.py
# encoding: utf-8
from django.db import models

class Clientes(models.Model):
    nombre = models.CharField(max_length = 255)
    apellidos = models.CharField(max_length = 255)
    edad = models.IntegerField()
    domicilio = models.CharField(max_length = 255)
    telefono = models.CharField(default=0, max_length=15)
    email = models.EmailField(null=True, blank=True)
    licencia = models.CharField(verbose_name="Numero Licencia", max_length=50)
    lic_vencimiento = models.DateField(verbose_name="Vencimiento de Licencia")
    lic_expedicion = models.DateField(verbose_name="Fecha de Expedición")
    tieneFiscal = models.BooleanField(verbose_name="Requiere Factura?")
    fis_nombre = models.CharField(max_length = 255, blank = True,
        verbose_name="Nombre Fiscal")
    fis_domicilio = models.CharField(max_length = 255, blank=True,
        verbose_name="Domicilio Fiscal", null=True)
    fis_rfc = models.CharField(max_length = 255, blank = True,
        verbose_name="RFC")
    fis_telefono = models.CharField(max_length = 255, blank = True,
        verbose_name="Telefono Fiscal")

    def __unicode__(self):
        return self.nombre + ' ' + self.apellidos

apps/ventas/models.py
from django.db import models
from apps.autos.models import Autos
from apps.clientes.models import Clientes
from django.contrib.auth.models import User
from datetime import datetime


class Ventas(models.Model): 
    """ 
    Modelo de Rentas de los autos
    Require modelos:
        Autos
        Clientes"""
    TIPOS_PAGO = (
        ('EFECTIVO','EFECTIVO'),
        ('TARJETA', 'TARJETA'),
        ('PENDIENTE', 'PENDIENTE'),
    )
    TIPOS_TARJETA = (
        ('VISA', 'VISA'),
        ('AMERICAN', 'AMERICAN EXPRESS'),
        ('MASTERCARD', 'MASTERCARD'),
    )
    SERIE = (
        ('C','C'), # Fiscal
        ('D', 'D'), # No fiscal
    )
    auto = models.ForeignKey(Autos)
    cliente = models.ForeignKey(Clientes)
    vendedor = models.ForeignKey(User)
    km_entrada = models.PositiveIntegerField(default=0)
    km_salida = models.PositiveIntegerField(default=0)
    km_recorridos = models.PositiveIntegerField(default=0)
    finalizada = models.BooleanField(default=False)
    fecha_salida = models.DateTimeField()
    created_at = models.DateTimeField(default=datetime.now())
    hora_extra = models.IntegerField(default = 0)
    fecha_entrada = models.DateTimeField(null=True)
    preciodia = models.FloatField(null=True, verbose_name="Precio Por Dia")
    seguro_accidentes = models.BooleanField(default=False)
    seguro_colision = models.BooleanField(default=False)
    tiene_conductor = models.BooleanField(default=False)
    nombre_conductor = models.CharField(max_length=500, blank=True, null=True)
    licencia_conductor = models.CharField(blank=True, null=True, max_length=100)
    lic_vencimiento_conductor = models.DateField(blank=True, null=True)
    lic_expedicion_conductor = models.DateField(blank=True, null=True)
    deposito = models.FloatField(default=0)
    adelanto = models.FloatField(default=0)
    iva = models.BooleanField(verbose_name="Con/Sin IVA")
    gas_octavos_entrada = models.IntegerField(null=True, 
                            verbose_name="Octavos de Gas")
    gas_octavos_salida = models.IntegerField(verbose_name="Octavos de Gas")
    reembolso = models.FloatField(default=0)
    total_iva = models.FloatField(default=0)
    total_horaextra = models.FloatField(default=0)
    total_dias = models.FloatField(default=0) # Dinero de renta
    total_gas = models.FloatField(default=0)
    total_seguros = models.FloatField(default=0)
    total_conductor = models.FloatField(default=0)
    total = models.FloatField(null=True)
    danios = models.FloatField(default=0)
    dias = models.PositiveIntegerField() # Numero dias que se rento
    tipo_pago = models.CharField(max_length=30, choices=TIPOS_PAGO)
    tarjeta = models.CharField(max_length=50, choices=TIPOS_TARJETA,
        verbose_name="Tipo de Tarjeta", null=True, blank=True)
    tar_vencimiento = models.DateField(verbose_name="Fecha Vencimiento", 
                                        null=True, blank=True)
    tar_numero = models.IntegerField(verbose_name="Numero Tarjeta", 
                                     blank=True ,null=True)
    num_contrato = models.PositiveIntegerField()
    serie = models.CharField(max_length=1, choices=SERIE)
    comentarios = models.TextField(max_length=255, blank=True)


class Reservaciones(models.Model):
    """
    Modelo de reservaciones
     Require modelos:
        Autos
        Clientes"""
    auto = models.ForeignKey(Autos)
    cliente = models.CharField(max_length=500, blank=True)
    fecha = models.DateTimeField()
    hotel = models.CharField(max_length=500, blank=True, 
            verbose_name="Hotel")
    num_cuarto = models.CharField(max_length=500, blank=True, 
            verbose_name="Num. Cuarto")
    anticipo = models.CharField(max_length=500, blank=True)
    comentarios = models.TextField(max_length=255, blank=True)
    created_at = models.DateTimeField(default=datetime.now())

apps/clientes/forms.py
from django import forms
from apps.clientes.models import Clientes


class ClientesForm(forms.ModelForm):
    class Meta:
        model = Clientes
        widgets = {
            'lic_vencimiento': forms.DateInput(attrs={'class': 'dp'}),
            'lic_expedicion': forms.DateInput(attrs={'class': 'dp'}),
            'edad': forms.TextInput(attrs={'class': 'span2'}),
            'nombre': forms.TextInput(attrs={'class': 'span6'}),
            'apellidos': forms.TextInput(attrs={'class': 'span6'}),
            'domicilio': forms.TextInput(attrs={'class': 'span8'}),
            'email': forms.TextInput(attrs={'class': 'span6'}),
            'fis_domicilio': forms.TextInput(attrs={'class': 'span8 disabled'}),
            'fis_nombre': forms.TextInput(attrs={'class': 'span6 disabled'}),
            'RFC': forms.TextInput(attrs={'class': 'disabled'}),
            'fis_telefono': forms.TextInput(attrs={'class': 'disabled'}),
        }

apps/clientes/views.py
from django.shortcuts import render_to_response, get_object_or_404, redirect, \
    get_list_or_404
from django.contrib.auth.decorators import permission_required, login_required
from django.template import RequestContext
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from apps.clientes.models import Clientes
from apps.clientes.forms import ClientesForm
from django.contrib import messages
from apps.eonutils.forms import DivErrorList
from django.core import serializers
from django.utils import simplejson
from django.http import HttpResponse
from django.db.models import Q


@login_required
def clientes(request):
    if request.method == 'POST':
        q = request.POST["q"]
        clientes = Clientes.objects.filter(
                            Q(nombre__icontains=q)|
                            Q(apellidos__icontains=q)
                            )
    else:
        clientes = Clientes.objects.all().order_by('nombre')
    paginator = Paginator(clientes, 30) 
    
     # Make sure page request is an int. If not, deliver first page.
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    # If page request (9999) is out of range, deliver last page of results.
    try:
        clientes_pagina = paginator.page(page)
    except (EmptyPage, InvalidPage):
        clientes_pagina = paginator.page(paginator.num_pages)
    
    vars = { 'clientes' : clientes_pagina }
    
    return render_to_response('clientes/clientes.html', vars,
                                 RequestContext(request))


@permission_required('clientes.delete_clientes')
def del_clientes(request, id):
    cliente = get_object_or_404(Clientes, pk = id)
    cliente.delete()
    messages.error(request, 'El Cliente ha sido eliminado')
    return redirect('/clientes/list')


@permission_required('clientes.add_clientes')
def add_clientes(request):
    if request.method == 'POST':
        form = ClientesForm(request.POST, error_class=DivErrorList)
        if form.is_valid():
            form.save()
            messages.success(request, 'El cliente ha sido agregado.')
            return redirect('/clientes/list/', 
                            context_instance = RequestContext(request))
    else:
        form = ClientesForm(error_class=DivErrorList)
    vars = {'form' : form}
    return render_to_response('clientes/add_clientes.html', vars,
                                    context_instance = RequestContext(request))


@permission_required('clientes.change_clientes')
def edit_clientes(request, id):
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    
    if request.method == 'POST':
        cliente = get_object_or_404(Clientes, pk = id)
        form = ClientesForm(request.POST, instance=cliente, 
                                    error_class=DivErrorList)
        if form.is_valid():
            form.save()
            messages.success(request, 'El cliente ha sido actualizado.')
            return redirect('/clientes/list/?page=' + str(page), 
                            context_instance = RequestContext(request))
    else:
        cliente = get_object_or_404(Clientes, pk = id)
        form = ClientesForm(instance=cliente, error_class=DivErrorList)
    vars = { 'form' : form, 'cliente' : cliente, 'page' : page }
    return render_to_response('clientes/change_clientes.html', vars,
                                context_instance = RequestContext(request))


@login_required
def detail_clientes(request, id):
    cliente = get_object_or_404(Clientes, pk = id)
    vars = { 'cliente' : cliente }
    return render_to_response('clientes/detail_clientes.html', vars,
                                context_instance = RequestContext(request))


@login_required
def api_get_client(request, id):
    client = get_list_or_404(Clientes, pk=id)
    json = serializers.serialize("json", client)
    return HttpResponse(simplejson.dumps(json), mimetype='application/javascript')

templates/clientes/add_clientes.html
{% extends 'default.html' %}

{%  block content%}
<h3>Agregar Cliente</h3>

    <form action="." class="well" method="POST"> {% csrf_token %}
        {{ form.non_field_errors }}
         <div class="">
            {{ form.nombre.errors|safe }}
            <label for="id_nombre">Nombre:</label>
            {{ form.nombre }}
        </div>
        <div class="">
            {{ form.apellidos.errors|safe }}
            <label for="id_apellidos">Apellidos:</label>
            {{ form.apellidos }}
        </div>
        <div class="">
            {{ form.edad.errors|safe }}
            <label for="id_edad">Edad:</label>
            {{ form.edad }}
        </div>
        <div class="">
            {{ form.domicilio.errors|safe }}
            <label for="id_domicilio">Domicilio:</label>
            {{ form.domicilio }}
        </div>
        <div class="">
            {{ form.telefono.errors|safe }}
            <label for="id_telefono">Telefono:</label>
            {{ form.telefono }}
        </div>
        <div class="">
            {{ form.email.errors|safe }}
            <label for="id_email">Email:</label>
            {{ form.email }}
        </div>
        <div class="">
            {{ form.licencia.errors|safe }}
            <label for="id_licencia">Numero de Licencia:</label>
            {{ form.licencia }}
        </div>
        <div class="">
            {{ form.lic_expedicion.errors|safe }}
            <label for="id_lic_expedicion">Fecha Expedicion Licencia:</label>
            {{ form.lic_expedicion }}
        </div>
        <div class="">
            {{ form.lic_vencimiento.errors|safe }}
            <label for="id_lic_vencimiento">Fecha Vencimiento Licencia:</label>
            {{ form.lic_vencimiento }}
        </div>
        
        <div class="">
            {{ form.tieneFiscal.errors|safe }}
            <label for="id_tieneFiscal">Requiere Factura?:</label>
            {{ form.tieneFiscal }}
        </div>
        
        <div id="factura">
            <div class="">
                {{ form.fis_nombre.errors|safe }}
                <label for="id_fis_nombre">Nombre Fiscal:</label>
                {{ form.fis_nombre }}
            </div>
            <div class="">
                {{ form.fis_domicilio.errors|safe }}
                <label for="id_fis_domicilio">Domicilio:</label>
                {{ form.fis_domicilio }}
            </div>
            <div class="">
            {{ form.fis_rfc.errors|safe }}
            <label for="id_fis_rfc">RFC:</label>
            {{ form.fis_rfc }}
        </div>
        <div class="">
            {{ form.fis_telefono.errors|safe }}
            <label for="id_fis_telefono">Telefono:</label>
            {{ form.fis_telefono }}
        </div>
        </div>
        
        <input type="submit" class="btn btn-success" value="Guardar" />
    </form>
{% endblock content %}

templates/clientes/change_clientes.html
{% extends 'default.html' %}

{%  block content%}
<h3>Editar Auto</h3>
	
	<form action="{% url apps.clientes.views.edit_clientes cliente.id %}" method="POST"> {% csrf_token %}
		{{ form.non_field_errors }}
		{{ form.errors }}
         <div class="">
            {{ form.nombre.errors }}
            <label for="id_nombre">Nombre:</label>
            {{ form.nombre }}
        </div>
        <div class="">
            {{ form.apellidos.errors }}
            <label for="id_apellidos">Apellidos:</label>
            {{ form.apellidos }}
        </div>
        <div class="">
            {{ form.edad.errors }}
            <label for="id_edad">Edad:</label>
            {{ form.edad }}
        </div>
        <div class="">
            {{ form.domicilio.errors }}
            <label for="id_domicilio">Domicilio:</label>
            {{ form.domicilio }}
        </div>
        <div class="">
            {{ form.telefono.errors }}
            <label for="id_telefono">Telefono:</label>
            {{ form.telefono }}
        </div>
        <div class="">
            {{ form.email.errors }}
            <label for="id_email">Email:</label>
            {{ form.email }}
        </div>
        <div class="">
            {{ form.licencia.errors }}
            <label for="id_licencia">Numero de Licencia:</label>
            {{ form.licencia }}
        </div>
        <div class="">
            {{ form.lic_expedicion.errors }}
            <label for="id_lic_expedicion">Fecha Expedicion Licencia:</label>
            {{ form.lic_expedicion }}
        </div>
        <div class="">
            {{ form.lic_vencimiento.errors }}
            <label for="id_lic_vencimiento">Fecha Vencimiento Licencia:</label>
            {{ form.lic_vencimiento }}
        </div>
        <div id="tarjeta">
            <div class="">
                {{ form.tarjeta.errors }}
                <label for="id_tarjeta">Tipo de Tarjeta:</label>
                {{ form.tarjeta }}
            </div>
            <div class="">
                {{ form.tar_numero.errors }}
                <label for="id_tar_numero"># Tarjeta:</label>
                {{ form.tar_numero }}
            </div>
            <div class="">
                {{ form.tar_vencimiento.errors }}
                <label for="id_tar_vencimiento">Fecha Vencimiento:</label>
                {{ form.tar_vencimiento }}
            </div>
        </div>
        
        <div class="">
            {{ form.tieneFiscal.errors }}
            <label for="id_tieneFiscal">Requiere Factura?:</label>
            {{ form.tieneFiscal }}
        </div>
        
        <div id="factura">
            <div class="">
                {{ form.fis_nombre.errors }}
                <label for="id_fis_nombre">Nombre Fiscal:</label>
                {{ form.fis_nombre }}
            </div>
            <div class="">
                {{ form.fis_domicilio.errors }}
                <label for="id_fis_domicilio">Domicilio:</label>
                {{ form.fis_domicilio }}
            </div>
            <div class="">
            {{ form.fis_rfc.errors }}
            <label for="id_fis_rfc">RFC:</label>
            {{ form.fis_rfc }}
        </div>
        <div class="">
            {{ form.fis_telefono.errors }}
            <label for="id_fis_telefono">Telefono:</label>
            {{ form.fis_telefono }}
        </div>
        </div>
        
		<input type="submit" class="btn btn-success" value="Guardar" />
	</form>
{% endblock content %}

templates/clientes/clientes.html
{% extends 'default.html' %}

{% block content %}
    {% if perms.clientes.add_clientes %}
        <span><a class="btn btn-primary" href="{% url apps.clientes.views.add_clientes %}"><i class="icon-plus icon-white"></i> Agregar</a></span>
    {% endif %}
        <div>
            <h2>Clientes</h2>
            <form class="well form-search" method="POST" action="."> {% csrf_token %}
              <input type="text" name="q" class="input-medium search-query">
              <button type="submit" class="btn">Buscar</button>
            </form>
        </div>
        <div class="row-fluid span10">
            <hr />
            <ul class="pager">
                {% if clientes.has_previous %}
                    <li class="previous">
                        <a href="?page={{ clientes.previous_page_number }}">&larr; Mas Nuevos</a>
                    </li>
                {% endif %}

                <span class="label label-info">
                    Pagina {{ clientes.number }} de {{ clientes.paginator.num_pages }}.
                </span>

                {% if clientes.has_next %}
                    <li class="next">
                        <a href="?page={{ clientes.next_page_number }}">Mas Antiguos &rarr;</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <div class="table table-striped  table-condensed table-bordered">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <th>Nombre</th>
                    <th>Apellidos</th>
                    <th>Edad</th>
                    <th>Telefono</th>
                    <th>Email</th>
                    <th>#Licencia</th>
                    <th>Vencimiento</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                {% for cliente in clientes.object_list %}
                    <tr>
                        
                        <td>{{ cliente.nombre }}</td>
                        <td>{{ cliente.apellidos }}</td>
                        <td>{{ cliente.edad }}</td>
                        <td>{{ cliente.telefono }}</td>
                        <td>{{ cliente.email }}</td>
                        <td>{{ cliente.licencia }}</td>
                        <td>{{ cliente.lic_vencimiento }}</td>
                        <td><a class="btn btn-info" href="{% url apps.clientes.views.detail_clientes cliente.id %}"><i class="icon-zoom-in icon-white"></i> Detalle</a></td>
                        {% if perms.clientes.change_clientes %}
                            <td><a class="btn btn-info" href="{% url apps.clientes.views.edit_clientes cliente.id %}"><i class="icon-pencil icon-white"></i> Editar</a></td>
                        {% endif %}
                        {% if perms.clientes.delete_clientes %}
                            <td><a class="btn btn-danger" href="{% url apps.clientes.views.del_clientes cliente.id %}"><i class="icon-trash icon-white"></i> Eliminar</a</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>
        </div>
{% endblock %}

templates/clientes/detail_clientes.html
{% extends 'default.html' %}

{% block content %}

    {% if perms.clientes.add_clientes %}
        <span><a class="btn btn-primary" href="{% url apps.clientes.views.add_clientes %}"><i class="icon-plus icon-white"></i> Agregar</a></span>
    {% endif %}
    <div class="box">
        <div>
            <h2>Cliente: {{ cliente.id }}</h2>
        </div>
                <ul>
                    <li>Nombre: {{ cliente.nombre }}</li>
                    <li>Apellidos: {{ cliente.apellidos }}</li>
                    <li>Edad: {{ cliente.edad }}</li>
                    <li>Telefono: {{ cliente.telefono }}</li>
                    <li>Email: {{ cliente.email }}</li>
                    <li>Licencia: {{ cliente.licencia }}</li>
                    <li>Vencimiento: {{ cliente.lic_vencimiento }}</li>
                    <li>Expedicion: {{ cliente.lic_expedicion }}</li>
                    <li>Nombre Fiscal: {{ cliente.fis_nombre }} </li>
                    <li>Domicilio: {{ cliente.fis_domicilio }} </li>
                    <li>RFC: {{ cliente.fis_rfc }} </li>
                    <li>Telefono: {{ cliente.fis_telefono }} </li>
                </ul>
                
                {% if perms.clientes.change_clientes %}
                    <a class="btn btn-info" href="{% url apps.clientes.views.edit_clientes cliente.id %}"><i class="icon-pencil icon-white"></i> Editar</a>
                {% endif %}
                {% if perms.clientes.delete_clientes %}
                    <a class="btn btn-danger" href="{% url apps.clientes.views.del_clientes cliente.id %}"><i class="icon-trash icon-white"></i> Eliminar</a>
                {% endif %}
           
        </div>
    </div>
{% endblock %}